source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
        end
    end
end

target 'MODE-iOSSDK_Example', :exclusive => true do
  pod "MODE-iOSSDK", :path => "../"
end

target 'MODE-iOSSDK_Tests', :exclusive => true do
  pod "MODE-iOSSDK", :path => "../"

  pod 'Kiwi'
end
